---
# tasks file for mongodb

- name: Add repository
  yum_repository:
    name: Mongodb-org-3.4
    description: Mongo repository
    baseurl: https://repo.mongodb.org/yum/redhat/{{ version_os }}/mongodb-org/3.4/x86_64/
    gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc
    gpgcheck: yes
    state: present

- name: Install Mongodb
  yum:
    name: mongodb-org
    state: present

- name: Config Mongodb standalone without auth
  template:
    src: "{{ role_path }}/templates/mongodb.conf-standalone-without-auth.j2"
    dest: "/etc/mongod.conf"
    owner: root
    group: root
    mode: 644
  notify: restart mongod

- name: Config data folders
  file: 
    state: directory
    path: "{{ mongo_data_path }}"
    recurse: yes
    owner: mongod
    group: mongod

- name: Config logs folders
  file:
    state: directory
    path: "{{ mongo_logs_path }}"
    recurse: yes
    owner: mongod
    group: mongod


