---
# tasks file for newrelic-php
- name: Add repo from NewRelic
  yum: 
    name: http://yum.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm
    state: present

- name: Install php-agent from Newrelic
  yum:
    name: "newrelic-php5"

- name: Copy config file newrelic.php
  template:
    src : newrelic.ini.j2
    dest: /etc/php.d/newrelic.ini
    force: yes
    owner: root
    group: root