---
# tasks file for php-fpm
# Setup/install tasks.
- include: setup-Amazon-Linux.yml
  when: ansible_distribution == 'Amazon'

- include: setup-RedHat.yml
  when: ansible_distribution == 'CentOS'



# - name: Base packages for php
#   yum:
#     name: "{{ item }}"
#     state: present
#     with_items: "{{ php_base_packages }}"