---
# tasks file for php-fpm
- name: Install repo for php
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    state: present

- name:  Install repo for php 2 REMI
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-6.rpm
    state: present

- name: Install PHP-FPM 
  yum:
  #example of name php71-php-fpm
    name: "php{{ version }}-php-fpm" 
    state: present

# - name: Base packages for php
#   yum:
#     name: "{{ item }}"
#     state: present
#     with_items: "{{ php_base_packages }}"